App:
  Environment: "prod"
  Id: "DTLS-DATA-PARSER"
  PathToWatch: "/home/results"
  ErrorParsePath: "/home/errorParse"
  Workers: 10
Kafka:
  Brokers: ["localhost:9092"]
  TopicsConsumer: ["security-assessment"]
  TopicsProducer: ["result-assessment"]
  TopicsError: ["security-assessment-error"]
  GroupID: "security-assessment-ingestion-group"
