App:
  Environment: "prod"
  Id: "DNS-ASSESSMENT"
  DNSServer: "1.1.1.1"
Kafka:
  Brokers: ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
  TopicsConsumer: ["evaluation-requests"]
  TopicsProducer: "evaluation-results"
  TopicsError: "security-assessment-error"
  GroupID: "security-assessment-dnssec-group"
  MaxRetry: 3
