App:
  Environment: "prod"
  Id: "STLS-ASSESSMENT"
  PathToResults: "/home/stls/results/"
kafka:
  Brokers: ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
  TopicsConsumer: ["evaluation-requests"]
  TopicsProducer: "evaluation-results"
  TopicsError: "security-assessment-error"
  GroupID: "security-assessment-https-group"
