App:
  Environment: "prod"
  Id: "DTLS-DATA-PARSER"
  PathToWatch: "/home/results"
  ErrorParsePath: "/home/error_parse"
  Workers: 10
Kafka:
  Brokers: ["kafka1:9092", "kafka2:9092", "kafka3:9092"]
  TopicsConsumer: ["evaluation-requests"]
  TopicsProducer: ["evaluation-results"]
  TopicsError: ["security-assessment-error"]
  GroupID: "security-assessment-ingestion-group"
  MaxRetry: 3
